#!/usr/bin/env bash

if
  [[ -s "/Users/dieguit/.rvm/gems/ruby-2.3.7/environment" ]]
then
  source "/Users/dieguit/.rvm/gems/ruby-2.3.7/environment"
  exec rougify "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/dieguit/.rvm/gems/ruby-2.3.7/environment'" >&2
  exit 1
fi
