#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
	if [ -d "$HOME/.iterm2" ]; then
		echo "Setting iTerm preference folder"
		defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
	fi

	brew install zsh
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
	chsh -s /opt/homebrew/bin/zsh

	brew install --cask wezterm

	brew install starship

	brew install neovim

fi
