" Include configs
source ~/.vim/plugins.vim
source ~/.vim/config/base.vim
source ~/.vim/config/coc.vim
source ~/.vim/config/denite.vim
source ~/.vim/config/mappings.vim
source ~/.vim/config/foldings.vim
source ~/.vim/config/nerdtree.vim
source ~/.vim/config/easymotion.vim
source ~/.vim/config/devicons.vim
source ~/.vim/config/ui.vim
source ~/.vim/config/airline.vim
source ~/.vim/config/highlight.vim

" Reload icons after init source
if exists('g:loaded_webdevicons')
  call webdevicons#refresh()
endif
