#!/usr/bin/env bash

if
  [[ -s "/Users/dieguit/.rvm/gems/ruby-2.3.7@global/environment" ]]
then
  source "/Users/dieguit/.rvm/gems/ruby-2.3.7@global/environment"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/dieguit/.rvm/gems/ruby-2.3.7@global/environment'" >&2
  exit 1
fi
