[[ -f ~/.zsh/tmp ]] && source ~/.zsh/tmp
[[ -f ~/.zsh/exports ]] && source ~/.zsh/exports
[[ -f ~/.zsh/alias ]] && source ~/.zsh/alias
[[ -f ~/.zsh/vimode ]] && source ~/.zsh/vimode

# Plugins
plugins=(git docker-compose)

# ZSH
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_COLOR_SCHEME='light'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vi_mode root_indicator background_jobs history time)

source $ZSH/oh-my-zsh.sh
